micronaut:
  application:
    name: magisterka
  server:
    cors:
      enabled: true
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: "MY_SECRET_SIGNATURE_AT_LEAST_256_LENGTH"

netty:
  default:
    allocator:
      max-order: 3

datasources:
  default:
    url: jdbc:mysql://localhost:3306/test
    dialect: MYSQL
    driverClassName: com.mysql.cj.jdbc.Driver
    username: "db-user"
    password: "db-pass"
    schema-generate: NONE

flyway:
  datasources:
    default:
      enabled: true

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true